### ISSUE TITLE
TypeError: include and exclude must both be non-string sequences

### ISSUE THREAD

**Issue by mikeoutlaw** [DataSciencePros/data_science_workshop#2]
When running the pandas_workshop notebook in [Azure Notebooks](http://notebooks.azure.com), the cell with the first use of seaborn throws the exception below. It seems that the `select_dtypes` implementation available in Azure is more finicky about list-like types being used.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-210-d2212fd5be04> in <module>()
      6 
      7 
----> 8 obj_cols=set(housing.select_dtypes(include='object').columns)
      9 heatmap_cols=[col for col in list(housing.columns) if col not in obj_cols]
     10 #set(untouched_cols).intersection(obj_cols)  #empty

~/anaconda3_420/lib/python3.5/site-packages/pandas/core/frame.py in select_dtypes(self, include, exclude)
   2345         include, exclude = include or (), exclude or ()
   2346         if not (is_list_like(include) and is_list_like(exclude)):
-> 2347             raise TypeError('include and exclude must both be non-string'
   2348                             ' sequences')
   2349         selection = tuple(map(frozenset, (include, exclude)))

TypeError: include and exclude must both be non-string sequences
```

**Comment by kulsoom-abdullah** [comment]
Interesting, I did not know about Azure notebooks.  From the [docs](https://pandas.pydata.org/pandas-docs/version/0.20/generated/pandas.DataFrame.select_dtypes.html),  a `TypeError` is raised _If either of include or exclude is not a sequence_.   
What happens if you specify both the include and exclude?  Like:
`housing.select_dtypes(include='object', exclude=['float','int']).columns`
I wonder if setting the exclude to a non object would help avoid that TypeError you are getting that both include and exclude have to be non-string.

**Comment by mikeoutlaw** [comment]
It seems that it is enough to just supply the include as a list-like object. See pull request #3.
